AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  todo-app

  Sample SAM Template for todo-app

Parameters:
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  TracingValue:
    Type: String
    Default: Active
  Stage:
    Type: String
    AllowedValues:
      - Prod
      - Staging
      - Dev
    Default: Prod
  MemorySize:
    Type: Number
    MinValue: 128
    MaxValue: 10240
    Default: 128  
  HelloWorldFunctionName:
    Type: String
    Default: hello-world
  BffFunctionName:
    Type: String
    Default: bff-function
  UsersFunctionName:
    Type: String
    Default: user-function    
  TodoFunctionName:
    Type: String
    Default: todo-function    
  LogLevel:
    Type: String
#    Default: INFO
    Default: DEBUG
  LogRetensionInDays:
    Type: Number
    Default: 7

Conditions:
  TracingEnabled: !Equals
    - !Ref TracingValue
    - Active

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:    
    Runtime: python3.12
    Architectures:
    - x86_64
    Timeout: 30
    MemorySize: !Ref MemorySize
    Tracing: !Ref TracingValue
    VpcConfig:
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-LambdaSecurityGroup-ID
      SubnetIds:
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetOneId
        - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetTwoId    
    Environment:
      Variables:   
        # Timezone
        TZ: Asia/Tokyo      
        # Power Tools Environment Variables        
        POWERTOOLS_LOG_LEVEL: !Ref LogLevel
        #POWERTOOLS_DEV: true
        #POWERTOOLS_LOGGER_LOG_EVENT: true
        #TODO: Add Environment Variables         
        DYNAMODB_LOCAL_ENDPOINT: ""
        TODO_TABLE_NAME: todo
        USERS_TABLE_NAME: users

    # Deployment Configurtion
    AutoPublishAlias: live
    DeploymentPreference:
      #Type: Linear10PercentEvery1Minute
      Type: AllAtOnce    
    Layers:
    # Powertools Lambda Layer
    - arn:aws:lambda:ap-northeast-1:017000801446:layer:AWSLambdaPowertoolsPythonV2:75
    # Application Common Lambda Layer
    - !Ref CommonLayer
    # AppConfig Extensions Lambda Layer    
    - arn:aws:lambda:ap-northeast-1:980059726660:layer:AWS-AppConfig-Extension:98 
    # Lambda Insights Extensions Lambda Layer    
    - arn:aws:lambda:ap-northeast-1:580247275435:layer:LambdaInsightsExtension:80

  Api:
    OpenApiVersion: 3.0.3
    TracingEnabled: !If [TracingEnabled, true, false]
    MethodSettings:
      - DataTraceEnabled: true
        LoggingLevel: ERROR
        ResourcePath: /*
        HttpMethod: '*'
    AccessLogSetting:
      Format: '{ "requestId":"$context.requestId", "extendedRequestId":"$context.extendedRequestId", "ip": "$context.identity.sourceIp", "caller":"$context.identity.caller", "user":"$context.identity.user", "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod", "resourcePath":"$context.resourcePath", "contextPath":"$context.path", "status":"$context.status", "protocol":"$context.protocol", "responseLength":"$context.responseLength", "integrationLatency":"$context.integration.latency", "responseLatency":"$context.responseLatency" }'      
      DestinationArn: !GetAtt ApiGwAccessLogGroup.Arn    
Resources:
# Lambda Layer
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${StackPrefix}-CommonLayer
      ContentUri: commonlayer
      CompatibleArchitectures:
        - x86_64
#        - arm64
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12
# Bff Function
  BffFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref BffFunctionName
      CodeUri: app/bff/
      Handler: app.lambda_handler
      Role: !ImportValue
        Fn::Sub: ${StackPrefix}-LambdaRoleArn
      Events:
        Event:
          Type: Api
          Properties:
            Path: /bff-api/{proxy+}
            Method: ANY
            RestApiId: !Ref BffApi
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: !Ref BffFunctionName
          TODO_API_BASE_URL: !Sub https://${TodoApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}
          USERS_API_BASE_URL: !Sub https://${UserApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}          
# Hello World Function
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Ref HelloWorldFunctionName
      CodeUri: app/hello_world/
      Handler: app.lambda_handler   
      Role: !ImportValue
        Fn::Sub: ${StackPrefix}-LambdaRoleArn         
      Events:
        Event:
          Type: Api 
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref HelloApi

# User Function
  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref UsersFunctionName
      CodeUri: app/users/
      Handler: app.lambda_handler       
      Role:
        Fn::ImportValue: !Sub ${StackPrefix}-LambdaRoleArn      
      Events:
        Event:
          Type: Api
          Properties:
            Path: /users-api/{proxy+}
            Method: ANY
            RestApiId: !Ref UserApi
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: !Ref UsersFunctionName

# Todo Function(API Triggered)
  TodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref TodoFunctionName
      CodeUri: app/todo/
      Handler: app.lambda_handler
      Role: !ImportValue
        Fn::Sub: ${StackPrefix}-LambdaRoleArn
      Events:
        Event:
          Type: Api
          Properties:
            Path: /todo-api/{proxy+}
            Method: ANY
            RestApiId: !Ref TodoApi
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: !Ref TodoFunctionName            

# API Gateway Private REST API
# Bff API(Regional Public API)
  BffApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: bff-api
      StageName: !Ref Stage
      EndpointConfiguration:
        Type: REGIONAL

# HelloWorld(Private API)
  HelloApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: hello-world-api
      StageName: !Ref Stage 
      EndpointConfiguration:
        Type: PRIVATE
        VPCEndpointIds:
          - Fn::ImportValue: !Sub ${StackPrefix}-PrivateAPIVPCEndpoint-ID
      Auth:
        ResourcePolicy:
          CustomStatements:
            - Effect: Allow
              Principal: '*'
              Action: execute-api:Invoke
              Resource: !Sub execute-api:/${Stage}/GET/hello              
              Condition:
                StringEquals:
                  aws:SourceVpce: !ImportValue
                    Fn::Sub: ${StackPrefix}-PrivateAPIVPCEndpoint-ID
# User API(Private API) 
  UserApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: user-api
      StageName: !Ref Stage
      EndpointConfiguration:
        Type: PRIVATE
        VPCEndpointIds:
          - Fn::ImportValue: !Sub ${StackPrefix}-PrivateAPIVPCEndpoint-ID
      Auth:
        ResourcePolicy:
          CustomStatements:
            - Effect: Allow
              Principal: '*'
              Action: execute-api:Invoke
              Resource:
                - !Sub execute-api:/${Stage}/POST/users-api/*
                - !Sub execute-api:/${Stage}/GET/users-api/*
              Condition:
                StringEquals:
                  aws:SourceVpce: !ImportValue
                    Fn::Sub: ${StackPrefix}-PrivateAPIVPCEndpoint-ID
# Todo API(Private API)
  TodoApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: todo-api
      StageName: !Ref Stage 
      EndpointConfiguration:
        Type: PRIVATE
        VPCEndpointIds:
          - Fn::ImportValue: !Sub ${StackPrefix}-PrivateAPIVPCEndpoint-ID
      Auth:
        ResourcePolicy:
          CustomStatements:
            - Effect: Allow
              Principal: '*'
              Action: execute-api:Invoke
              Resource:
                - !Sub execute-api:/${Stage}/POST/todo-api/*
                - !Sub execute-api:/${Stage}/GET/todo-api/*
              Condition:
                StringEquals:
                  aws:SourceVpce: !ImportValue
                    Fn::Sub: ${StackPrefix}-PrivateAPIVPCEndpoint-ID

# IAM Role for API Gateway Account
  APIGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
# API Gateway Account Config
  ApiGwAccountConfig:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt APIGatewayRole.Arn
# API Gateway Access Log Group
  ApiGwAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/accesslog/${AWS::StackName}
      RetentionInDays: !Ref LogRetensionInDays
# Lambda Log group
  HelloWorldFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${HelloWorldFunctionName}
      RetentionInDays: !Ref LogRetensionInDays
  UsersFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${UsersFunctionName}
      RetentionInDays: !Ref LogRetensionInDays      
  TodoFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${TodoFunctionName}
      RetentionInDays: !Ref LogRetensionInDays
  BffFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${BffFunctionName}
      RetentionInDays: !Ref LogRetensionInDays

# Application Insights
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  HelloWorldAPI:
    Description: API Gateway endpoint URL for HelloWorld
    Value: !Sub https://${HelloApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/hello
  HelloWorldFunction:
    Description: First Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  BffAPI:
    Description: API Gateway endpoint URL for Bff
    Value: !Sub https://${BffApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/bff-api
  BffFunction:
    Description: Bff Lambda Function ARN
    Value: !GetAtt BffFunction.Arn
  BffFunctionDeploymentGroup:
    Description: Bff Lambda Function DeploymentGroup ARN
    Value: !Ref BffFunctionDeploymentGroup
  UsersAPI:
    Description: API Gateway endpoint URL for Users
    Value: !Sub https://${UserApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/users-api/v1/users
  UsersFunction:
    Description: Users Lambda Function ARN
    Value: !GetAtt UsersFunction.Arn
  UsersFunctionDeploymentGroup:
    Description: Users Lambda Function DeploymentGroup ARN
    Value: !Ref UsersFunctionDeploymentGroup    
  TodoAPI:
    Description: API Gateway endpoint URL for Todo
    Value: !Sub https://${TodoApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/todo-api/v1/todo
  TodoFunction:
    Description: Todo Lambda Function ARN
    Value: !GetAtt TodoFunction.Arn
  TodoFunctionDeploymentGroup:
    Description: Todo Lambda Function DeploymentGroup ARN
    Value: !Ref TodoFunctionDeploymentGroup    